frame: cqlvalue, added support for Set<Text>
mmatczuk/scylla-go-driver pull request #168
Opened 2022-03-21 17:58 UTC by Kulezi

@Michal-Leszczynski mentioned the need for parsing lists of token strings in cluster, those are actually of `set<text>` type.
This PR adds CqlValue.AsTextSet() allowing parsing token sets.

Also I think that validating correctness of CqlValue underlying bytes (e.g. checking if strings are utf8) should be done only when Debug flag is set, as we shouldn't get invalid data from queries. Correct me if I'm wrong.

2022-03-25 10:01 UTC, mmatczuk commented
Naming, can we use String instead of Text and Slice instead of Set i.e. []string is StringSlice.
This is a general comment applies to some existing code too.

2022-03-25 10:03 UTC, mmatczuk commented
Also, technically CqlFromTextSet creates a List?
A more flexible naming convention is needed.

2022-03-25 16:18 UTC, Michal-Leszczynski requested changes

2022-03-25 16:18 UTC, Michal-Leszczynski commented on frame/cqlvalue.go
> +	if c.Type.ID != SetID || c.Type.List.Element.ID != VarcharID {
I get errors when using this function. There should be:
`c.Type.Set.Element.ID`
instead of:
`c.Type.List.Element.ID`

2022-03-27 17:08 UTC, Kulezi commented
Renamed to AsStringSlice(), this feels more natural, it allows parsing from lists and sets of varchar, text and ascii types.

2022-03-27 18:01 UTC, Choraden approved these changes

2022-03-29 08:37 UTC, Michal-Leszczynski approved these changes

2022-04-01 09:36 UTC, closed without merging

2022-04-01 11:14 UTC, Kulezi commented
Merged with #179